import React from 'react';
import { Metadata } from 'next';
import LoginPage from '@/components/templetes/pageSection/LoginPage';

export const metadata: Metadata = {
    title: "Sign In",
    description: "Generated by usman developer",
};
const page = () => {

    return (
        <>
            <LoginPage />
        </>
    )
}

export default page;