import LoginPage from '@/components/templetes/pageSection/LoginPage';
import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
    title: "Sign In",
    description: "Generated by create next app",
};
const page = () => {

    return (
        <>
            <LoginPage />
        </>
    )
}

export default page;