import type { Metadata } from "next";
import './globals.css';
import { Providers } from "@/components/store/Provider";

export const metadata: Metadata = {
  title: "App Write Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
