import React from 'react'
import { Metadata } from 'next';
import DetailsMain from '@/components/templetes/pageSection/DetailsMain';


export const metadata: Metadata = {
    title: "Rooms Detail",
    description: "Generated by usman developer",
};
const page = ({ params }: { params: any }) => {
    return (
        <DetailsMain id={params.id} />
    )
}

export default page;