import React from "react";
import { Metadata } from "next";
import DetailsMain from "@/components/templetes/pageSection/DetailsMain";

export const metadata: Metadata = {
    title: "Rooms Detail",
    description: "Generated by Usman Developer",
};

// ✅ Make it an async function to await params
const Page = async ({ params }: { params?: { id?: string | null | undefined } }) => {
    return <DetailsMain id={params?.id ?? ''} />
};

export default Page;
