import React from 'react';
import { Metadata } from 'next';
import SignupPage from '@/components/templetes/pageSection/SignupPage';

export const metadata: Metadata = {
  title: 'Sign Up',
  description: "Generated by usman developer",
};

const page = () => {
  return <SignupPage />;
};

export default page;
